spring:
  # ?????
  datasource:
    username: root
    password: 2017727
    url: jdbc:mysql://192.168.2.130:3306/ESDB
    type: com.alibaba.druid.pool.DruidDataSource
  elasticsearch:
    connection-timeout: 3s
    uris: http://192.168.2.130:9200 #ES ?????

server:
  port: 9021

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml


logging:
  level:
    com.baomidou: debug
    com.baomidou.mybatisplus: debug
    com.baomidou.dynamic: debug
    com.vincent.esspringboot.*: debug
    org.mybatis: debug
    org.springframework.jdbc.core: debug
    org.elasticsearch.client.RestHighLevelClient: DEBUG
