spring:
  # ?????
  datasource:
    username: root
    password: 2017727
    url: jdbc:mysql://192.168.2.130:3306/ESDB
    type: com.alibaba.druid.pool.DruidDataSource
  elasticsearch:
    connection-timeout: 3s
    uris: http://192.168.2.130:9200 #ES ?????

server:
  port: 9021

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    com.example.elastic: debug